name: Terraform CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init -backend=false
      - name: Terraform Format
        run: terraform fmt -check -recursive
      - name: Terraform Validate
        run: terraform validate

  deploy-test:
    needs: validate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Arrancar Docker
        run: |
          sudo systemctl start docker
          docker ps
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        env:
          TF_VAR_nginx_port: 8080
          TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
        run: terraform plan -no-color -input=false
      - name: Terraform Apply
        env:
          TF_VAR_nginx_port: 8080
          TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
        run: terraform apply -auto-approve -input=false
      - name: Verificar contenedores
        run: |
          sleep 10
          curl -f http://localhost:8080 || exit 1
          docker ps | grep web
          docker ps | grep db
          docker ps | grep adminer
      - name: Terraform Destroy
        if: always()
        env:
          TF_VAR_nginx_port: 8080
          TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
        run: terraform destroy -auto-approve -input=false
